#!/bin/bash

# Ensure dub-data-mod is built
cd $3
dub build

# Ensure safearg is built
cd $4
dub build

# Compile
cd $2
$3bin/dub-data-mod describe --compiler=dmd --config=tests --data-0 --data=options --data=versions --data=import-paths | $4bin/safearg --post=src/instauser/$1/package.d rdmd -unittest -main --force
