#!/bin/sh

# Ensure ddox is built
cd $4
dub build

# Build docs
echo Generating instauser-$1 docs...
cd $2
rdmd -I../InstaUser-Basic/src -I../InstaUser-Store/src -I../InstaUser-Web/src -Ires -Jres --build-only --force -c -Dddocs_tmp -X -Xfdocs/docs.json -version=InstaUser_Docs src/instauser/$1/package.d
rm -rf docs_tmp
rm -f src/instauser/$1/package
$4/ddox filter docs/docs.json --min-protection=Protected
$4/ddox generate-html docs/docs.json docs/public --navigation-type=ModuleTree
