#!/bin/sh

# Ensure ddox is built
cd $3
dub build

# Build docs
echo Generating instauser-$1 docs...
cd $2
rdmd -Isrc --build-only --force -c -Dddocs_tmp -X -Xfdocs/docs.json -version=InstaUser_Docs src/instauser/$1/package.d
rm -rf docs_tmp
rm -f src/instauser/$1/package
$3/ddox filter docs/docs.json --min-protection=Protected
$3/ddox generate-html docs/docs.json docs/public --navigation-type=ModuleTree
