sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.081.1
 - dmd-2.080.1
 - dmd-2.079.1
 - dmd-2.078.3
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1
 - dmd-2.073.2
 - dmd-2.072.2
 - dmd-2.071.2
 - dmd-2.070.2
 - dmd-2.069.2
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-1.10.0
 - ldc-1.9.0
 - ldc-1.8.0
 - ldc-1.7.0
 - ldc-1.6.0
 - ldc-1.5.0
 - ldc-1.4.0
 - ldc-1.3.0
 - ldc-1.2.0
 - ldc-1.1.1
 - ldc-1.0.0
 - ldc-0.17.2
 - ldc-0.16.1
 - ldc-0.15.1
 - gdc
 - dmd-beta
 - ldc-beta
 - dmd
 - ldc

matrix:
  allow_failures:
   - os: osx
     d: gdc
   - d: dmd-beta
   - d: ldc-beta

script:
 - dub test
 - ./run_unittests
