#!/bin/sh
dmd -Isrc -c -op -Dddocs -version=Have_mysql_native -version=Have_vibe_d "$@" src/instauser/package.d src/instauser/core.d src/instauser/store/memory.d src/instauser/store/mysqln.d
mv docs/src/instauser/package.html docs/src/instauser/index.html
